import {
  ArrowLeftRight,
  Bookmark,
  BookOpenText,
  Briefcase,
  CalendarClock,
  CalendarDays,
  CalendarRange,
  CircleCheck,
  Compass,
  Contact,
  DoorOpen,
  FileCheck,
  Hammer,
  Heart,
  Home,
  Info,
  Landmark,
  LayoutDashboard,
  LayoutGrid,
  ListChecks,
  ListTodo,
  Luggage,
  NotebookPen,
  NotebookText,
  Package,
  PiggyBank,
  Plane,
  Receipt,
  Repeat,
  Sparkles,
  Star,
  Tags,
  Target,
  Ticket,
  Users,
  Wallet,
  Wrench,
} from "lucide-react";
import type { LucideIcon } from "lucide-react";

import type { PlannerWorkspaceIconKey } from "@/types/planner-workspace";

/**
 * Resolves a `PlannerWorkspace`/`PlannerWorkspaceNavItem`'s serializable
 * `iconKey` back into a real `LucideIcon` - see `@/types/planner-workspace`'s
 * own comment for why the data itself carries a string key rather than the
 * component reference. A plain, framework-agnostic module (no `"use client"`,
 * no `server-only`) so both `DashboardSidebar` (Server Component) and
 * `PlannerWorkspaceNav` (Client Component) can import it directly.
 */
export const PLANNER_WORKSPACE_ICONS: Record<PlannerWorkspaceIconKey, LucideIcon> = {
  dashboard: Heart,
  checklist: ListChecks,
  timeline: CalendarClock,
  budget: PiggyBank,
  guests: Users,
  vendors: Briefcase,
  events: CalendarRange,
  notes: NotebookText,
  generic: NotebookPen,
  overview: LayoutDashboard,
  income: Wallet,
  expenses: Receipt,
  goals: Target,
  recurring: Repeat,
  transactions: ArrowLeftRight,
  categories: Tags,
  accounts: Landmark,
  trip: Plane,
  itinerary: Compass,
  bookings: Ticket,
  packing: Luggage,
  documents: FileCheck,
  information: Info,
  home: Home,
  contacts: Contact,
  rooms: DoorOpen,
  inventory: Package,
  important: Star,
  maintenance: Wrench,
  bills: Receipt,
  projects: Hammer,
  life: Sparkles,
  areas: LayoutGrid,
  tasks: ListTodo,
  routines: Repeat,
  habits: CircleCheck,
  planning: CalendarDays,
  journal: BookOpenText,
  importantInfo: Bookmark,
};
